/**
 * Simlish Dictionary Data - Complete embedded data
 * Priority: Full phrases → Individual words → Fallback synonyms → Syllable generation
 */

window.SimlishData = {
    dictionary: {
        "phrases": {
            // ===== FULL PHRASES (HIGHEST PRIORITY) =====

            // Luke Bryan - Country Girl (Shake It For Me) - COMPLETE SONG
            "shake it for the catfish swimmin' down deep in the creek": "sheeky fa va googlix sima fown ippy ni crease",
            "shake it for the young bucks sittin' in the honky-tonks": "sheeky fa va yum plicks sibbin' ona hurky durks",
            "for the crickets and the critters and the squirrels": "fa va crickles imma priffa nima squirn",
            "for the rednecks rockin' 'til the break of dawn": "fa va rimbicks ricky illa bappy durf",
            "with a gattle in her bud to get a little wild": "godda limma bubbly gidi linna wile",
            "shake it for the birds, shake it for the bees": "sheeky fa va burs sheeky fa va bweez",
            "in the wind on the hill underneath the pines": "emba wee noody hill ooraneeb fwoo praj",
            "feel the kick drum down deep in your toes": "feeba keep drodown hibba batoose",
            "get up on the hood of my daddy's tractor": "gidop oona hoo um ma deedee aptur",
            "gonna stomp my boots in the georgia mud": "yibba skom bake nukes iffa jurja muv",
            "so come on over here and get in my arms": "sakee ania hee ingod neezarns",
            "gonna open up the doors and turn it up": "galba ooba nara doona turnip nerb",
            "somebody's sweet little farmer's child": "so-gidda seep widdy farma shile",
            "girl, shake it for me, ah country girl": "gurn, sheeky fa vee (oh crumply gurn!)",
            "you know you've got everybody lookin'": "yinna wona koo ibby bana locky",
            "for the dj spinnin' that country song": "fa va gj scooby snack crumply snurf",
            "gonna watch you make me fall in love": "gibba wan choof meep meep falva luv",
            "all i wanna do is get to holdin' you": "ahobee wabba noosa gebba hurna voo",
            "up on the tool box, it don't matter": "dock oona toobig ee boo madder",
            "got a little boom in my big truck": "galba libba bloom inna pik turb",
            "the dj spinnin' that country song": "fa va gj scooby snack crumply snurf",
            "aw, country girl, shake it for me": "aw crumply gurn sheeky fa vee",
            "shake it to the moon, shake it for me girl": "sheeky dawa moon, sheeky fa vee gurn!",
            "spin me around this big ole barn": "spinny arose zit dinfo blarn",
            "tangle me up like grandma's yarn": "teegala muff lee gurnbo's yarn",
            "yeah, move like the river flows": "yibs moo, loka ribby fool",
            "rope me in from a country mile": "rootinny yib frooma crumply mile",
            "country girl, shake it for me": "crumply gurn sheeky fa vee",
            "pony-tail and a pretty smile": "nobeeday ina pibly smurf",
            "now dance, like a dandelion": "noo densh laika durndilurn",
            "to watch you do your thing": "too wop choo dooda theen",
            "'fore the night is through": "forda nie bessoo",
            "baby, you know what to do": "nooboo noovet wonchizoo!",
            "and get to knowin' you": "sa gebba nooba voo",
            "and get to showin' you": "sa gebba shoova goo",
            "and get to lovin' you": "ye gebba lurvy voo",
            "girl, shake it for me": "gurn sheeky fa vee",
            "hey girl, go on now!": "hee gurn...go um bow...",
            "down on the tailgate": "doo nana taykay",
            "c'mon, c'mon, c'mon": "sim on sim on sim on!",
            "girl i can't wait": "gurn akeg way",
            "yeah, yeah, yeah": "yibs yibs yibs!",

            // Pussycat Dolls - Don't Cha
            "don't cha wish your girlfriend was hot like me": "doba uisli giog no uog no logi",

            // Lily Allen - Smile  
            "when you first left me i was wanting more": "wanufi lepto aba wabwa moops",
            "but you were fucking that girl next door": "bayawa flooping ta gooni doo",
            "at first when i see you cry": "kofui isabasi bug fui",
            "yeah it makes me smile": "livawop asmil",
            "i can feel the pressure": "yeah feel all but sur bri",
            "what'cha do that for": "waja dawa foops",
            "can this be real": "k-me nes ra shen",

            // Multi-word phrases
            "will you marry me": "vanu marsha ma",
            "i think you're hot": "za woka genava",
            "i have to pee": "atohteh",
            "i'm on fire": "wabadebadoo",
            "i love this": "jadosi",
            "i look hot": "ravasheen",
            "let's play": "veena fredishay",
            "i'm bored": "uhh shamoo ralla poo",
            "i'm hungry": "oh feebee lay",
            "i'm pregnant": "o mee pooba",
            "this is cool": "whippna choba dog",
            "how are you": "cuhteekaloo",
            "i love you": "por see gab lurv",
            "when's lunch": "vens unch",
            "great idea": "ah gwanda blitz",
            "good morning": "sul sul",
            "see you later": "dag dag",
            "good night": "dag dag",
            "thank you": "vadish",
            "best friend": "yibsim",
            "good day": "maladai",
            "don't cha": "doba",
            "don't you": "doba",
            "take off": "taka oof",
            "marry me": "vanu marsha ma",
            "shake it for me": "sheeky fa vee",
            "shake it": "sheeky",
            "country girl": "crumply gurn",
            "for me": "fa vee",

            // ===== INDIVIDUAL WORDS (SECOND PRIORITY) =====
            // Extracted from Country Girl (Luke Bryan)
            "catfish": "googlix",
            "swimmin'": "sima",
            "swimming": "sima",
            "creek": "crease",
            "young": "yum",
            "bucks": "plicks",
            "sittin'": "sibbin'",
            "sitting": "sibbin'",
            "honky-tonks": "hurky durks",
            "crickets": "crickles",
            "critters": "priffa",
            "squirrels": "squirn",
            "rednecks": "rimbicks",
            "rockin'": "ricky",
            "rocking": "ricky",
            "break": "bappy",
            "dawn": "durf",
            "birds": "burs",
            "bees": "bweez",
            "gattle": "godda",
            "wild": "wile",
            "wind": "wee",
            "hill": "hill",
            "underneath": "ooraneeb",
            "pines": "praj",
            "kick": "keep",
            "drum": "drodown",
            "toes": "batoose",
            "hood": "hoo",
            "daddy's": "deedee",
            "daddy": "deedee",
            "tractor": "aptur",
            "gonna": "yibba",
            "stomp": "skom",
            "boots": "bake nukes",
            "georgia": "jurja",
            "mud": "muv",
            "come": "sakee",
            "over": "ania",
            "here": "hee",
            "get": "gidop",
            "arms": "neezarns",
            "open": "ooba",
            "doors": "doona",
            "turn it": "turnip",
            "somebody's": "so-gidda",
            "somebody": "so-gidda",
            "sweet": "seep",
            "little": "widdy",
            "farmer's": "farma",
            "farmer": "farma",
            "child": "shile",
            "know": "wona",
            "you've": "yinna",
            "got": "koo",
            "everybody": "ibby bana",
            "lookin'": "locky",
            "looking": "locky",
            "spinnin'": "scooby snack",
            "spinning": "scooby snack",
            "song": "snurf",
            "watch": "wan choof",
            "make": "meep meep",
            "fall": "falva",
            "wanna": "wabba",
            "holdin'": "hurna",
            "holding": "hurna",
            "tool": "toobig",
            "box": "ee boo",
            "don't": "ee",
            "matter": "madder",
            "boom": "bloom",
            "big": "pik",
            "truck": "turb",
            "moon": "moon",
            "spin": "spinny",
            "around": "arose",
            "barn": "blarn",
            "tangle": "teegala",
            "grandma's": "gurnbo's",
            "grandma": "gurnbo",
            "yarn": "yarn",
            "yeah": "yibs",
            "move": "moo",
            "like": "loka",
            "river": "ribby",
            "flows": "fool",
            "rope": "rootinny",
            "mile": "mile",
            "country": "crumply",
            "girl": "gurn",
            "shake": "sheeky",
            "pony-tail": "nobeeday",
            "pretty": "pibly",
            "smile": "smurf",
            "now": "noo",
            "dance": "densh",
            "dandelion": "durndilurn",
            "do": "dooda",
            "your": "choo",
            "thing": "theen",
            "'fore": "forda",
            "night": "nie",
            "through": "bessoo",
            "baby": "nooboo",
            "what": "wonchizoo",
            "knowin'": "nooba",
            "knowing": "nooba",
            "showin'": "shoova",
            "showing": "shoova",
            "lovin'": "lurvy",
            "loving": "lurvy",
            "hey": "hee",
            "go": "go",
            "down": "doo",
            "tailgate": "taykay",
            "c'mon": "sim on",
            "can't": "akeg",
            "wait": "way",

            // Other common words
            "music": "musika",
            "girlfriend": "no uog",
            "delicious": "deileesh",
            "excited": "whippna choba dog",
            "wedding": "noobtia",
            "cheers": "shpansa",
            "goodbye": "dag dag",
            "problem": "shooflee",
            "nothing": "neebie",
            "nobody": "neeb-simsie",
            "clothes": "cwose",
            "hello": "sul sul",
            "please": "plerg",
            "thanks": "vadish",
            "sorry": "oh feebee lay",
            "angry": "benzi chibna looble bazebni gweb",
            "where": "wabadebadoo",
            "gross": "des grobel",
            "funny": "garsha",
            "freak": "uozzi",
            "happy": "ooh be gah",
            "friend": "sim",
            "when": "geelfrob",
            "fire": "zep tor maboo",
            "love": "meshaloob",
            "help": "shooflee",
            "wish": "uisli",
            "heat": "haspa",
            "burn": "haspa",
            "ain't": "nay",
            "yes": "yibs",
            "bye": "dag dag",
            "sad": "awasa poa",
            "why": "za woka genava",
            "how": "hooba noobie",
            "hot": "haspa",
            "raw": "naaao",
            "fun": "big fu",
            "no": "neib",
            "hi": "sul sul",
            "my": "ya",
            "i": "yob"
        },
        "fallbackSynonyms": {
            "deep": "zoo",
            "dark": "grob",
            "bright": "shina",
            "soft": "soffa",
            "hard": "harda",
            "fast": "fasta",
            "slow": "slowa",
            "quick": "fasta",
            "large": "pik",
            "huge": "pik",
            "tiny": "libba",
            "small": "libba"
        }
    },

    contextualPhrases: {
        "i love you": [
            { "simlish": "por see gab lurv", "context": ["so", "much", "really", "truly", "deeply"], "weight": 1.5 },
            { "simlish": "meshaloob", "context": ["baby", "babe", "honey", "darling"], "weight": 1.2 }
        ],
        "love": [
            { "simlish": "meshaloob", "context": ["i", "you", "we", "my", "your"], "weight": 1.5 }
        ]
    },

    semanticCategories: {
        "movement": { "simlish": "zooma", "words": ["walk", "run", "move", "go", "travel"] },
        "communication": { "simlish": "yabba", "words": ["talk", "speak", "say", "tell", "chat"] },
        "eating": { "simlish": "nomnom", "words": ["eat", "consume", "devour", "munch"] },
        "sleeping": { "simlish": "slerp", "words": ["sleep", "rest", "nap", "snooze"] },
        "happiness": { "simlish": "ooh be gah", "words": ["happy", "joyful", "cheerful", "glad"] },
        "sadness": { "simlish": "awasa poa", "words": ["sad", "unhappy", "depressed"] }
    }
};

console.log('✅ Simlish data loaded:', Object.keys(window.SimlishData.dictionary.phrases).length, 'phrases');
